services:
  - type: web
    name: telegram-autoresponder
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: sh start.sh
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /health
    port: 10000
